### ISSUE TITLE
 [Metamask] call contract vote() function

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/dapp#53]
When user selects chooses an option ( `yes` or `no`) and then clicks on the `vote` button it triggers a metamask transaction. Vote function parameters are vote(aremsg.sender, ballotId, voteOption)
- [x] implement API call with web3.js and construct transaction.
- [x] The UI should show the state of the transaction.

**Comment by virgile-dev** [comment]
Transaction status:
<img width="982" alt="capture d ecran 2018-04-22 a 13 57 24" src="https://user-images.githubusercontent.com/11473995/39094781-9f3ea7d8-4635-11e8-8100-d8a127f2f147.png">

**Comment by aecc** [comment]
This was actually already implemented in #54. The UI still doesn't show the transaction progress. I'm not sure how to make that work @AlexJupiter @LucasIsasmendi

**Comment by aecc** [comment]
@AlexJupiter @LucasIsasmendi should we leave the "transaction in progress" to be implemented in this issue?

**Comment by AlexJupiter** [comment]
@aecc, I believe so yes. It isn't recorded in any other ticket.

**Comment by aecc** [comment]
ok, I leave this to you guys because I have no idea how to do it. The ideal scenario would be that the modal is not blocking, and that after clicking "submit", the progress is in the background (meanwhile you can browse) and some kind of notification is obtained when the transaction is done (remember we are talking about minutes in the main net)
I wonder, is this how we envisioned it in the UX design initially? is this part of the scope of dapp 0.2 ?
Or should we do a "blocking" modal for this iteration?
I lean more towards the last option.

**Comment by AlexJupiter** [comment]
Closing this issue, to celebrate that this task has been done, and then going to open a new issue just related to the transaction statuses.

**Comment by AlexJupiter** [comment]
Related issue: https://github.com/DemocracyEarth/dapp/issues/90
